### ISSUE TITLE
dev label

### ISSUE THREAD

**Issue by mydevpeeps** [Duet3D/DuetWebControl#286]
I'm a little new to the mechanics of github communication methods and I don't really see a way to directly communicate with anyone other than filing an issue. 

Would it be possible to make a "dev" label for issues that could be used to make comments/discussion about the current dev branch?

**Comment by chrishamm** [comment]
I do not see much need in discussing pending changes in the dev branch because things are expected to change quite frequently in there. Things may be broken in this branch (which I may or may not be aware of) so I do not advise anyone to try it out before I actually announce a beta/stable version.

For example getting additionally built webpack chunks to load dynamically took longer than I anticipated, so there is no official beta out there yet. When it is out, feel free to share comments/ideas in the corresponding thread on the [forum](https://forum.duet3d.com).
